name: Update library branch

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  call-lv-update-library:
    name: Call "Update library branch"
    uses: sw4sys/.github/.github/workflows/lv-update-library.yml@master
    permissions:
      contents: write
